In [110]:
import numpy as np
import pandas as pd


from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report
from sklearn.metrics import f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [73]:
data = pd.read_csv('/kaggle/input/top-women-chess-players/top_women_chess_players_aug_2020.csv')

In [74]:
data.head()

,Fide id,Name,Federation,Gender,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,700070,"Polgar, Judit",HUN,F,1976.0,GM,2675,2646.0,2736.0,wi
1,8602980,"Hou, Yifan",CHN,F,1994.0,GM,2658,2621.0,2601.0,NaN
2,5008123,"Koneru, Humpy",IND,F,1987.0,GM,2586,2483.0,2483.0,NaN
3,4147103,"Goryachkina, Aleksandra",RUS,F,1998.0,GM,2582,2502.0,2441.0,NaN
4,700088,"Polgar, Susan",HUN,F,1969.0,GM,2577,NaN,NaN,wi

In [75]:
data.drop(['Fide id' , 'Name' , 'Gender' , 'Federation'] , axis=1 , inplace=True)

In [76]:
data.isnull().sum()

Year_of_birth       292
Title              5435
Standard_Rating       0
Rapid_rating       4945
Blitz_rating       5081
Inactive_flag      2701
dtype: int64

In [77]:
data['Blitz_rating'] = data['Blitz_rating'].fillna(data['Blitz_rating'].mean())

In [78]:
data['Blitz_rating'] = data['Blitz_rating'].fillna(data['Blitz_rating'].mean())

In [79]:
data

,Year_of_birth,Title,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag
0,1976.0,GM,2675,2646.0,2736.000000,wi
1,1994.0,GM,2658,2621.0,2601.000000,NaN
2,1987.0,GM,2586,2483.0,2483.000000,NaN
3,1998.0,GM,2582,2502.0,2441.000000,NaN
4,1969.0,GM,2577,NaN,1925.155242,wi
...,...,...,...,...,...,...
8548,NaN,NaN,1801,NaN,1925.155242,wi
8549,1994.0,NaN,1801,1791.0,1765.000000,NaN
8550,1992.0,NaN,1801,1884.0,1824.000000,wi
8551,2001.0,WFM,1801,NaN,1925.155242,wi
8552,1982.0,NaN,1801,NaN,1925.155242,wi

In [80]:
data[data[np.nan]]

KeyError: nan

In [ ]:
data[data['Year_of_birth'].isna()]

In [ ]:
data.drop(data[data['Year_of_birth'].isna()])

In [ ]:
n

In [81]:
gm = pd.get_dummies(data['Title'])
data = pd.concat([data , gm['GM']],axis=1)
data.drop('Title',axis=1,inplace=True)

In [94]:
data

,Year_of_birth,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag,GM
0,1976.000000,2675,2646.0,2736.000000,wi,True
1,1994.000000,2658,2621.0,2601.000000,wi,True
2,1987.000000,2586,2483.0,2483.000000,wi,True
3,1998.000000,2582,2502.0,2441.000000,wi,True
4,1969.000000,2577,NaN,1925.155242,wi,True
...,...,...,...,...,...,...
8548,1985.291732,1801,NaN,1925.155242,wi,False
8549,1994.000000,1801,1791.0,1765.000000,wi,False
8550,1992.000000,1801,1884.0,1824.000000,wi,False
8551,2001.000000,1801,NaN,1925.155242,wi,False
8552,1982.000000,1801,NaN,1925.155242,wi,False

In [83]:
data['Inactive_flag'] = data['Inactive_flag'].fillna('wi',axis=0)

In [99]:
data['Rapid_rating'] = data['Rapid_rating'].fillna(data['Rapid_rating'].mean())

In [84]:
data['Year_of_birth'] = data['Year_of_birth'].fillna(data['Year_of_birth'].mean())

In [102]:
data

,Year_of_birth,Standard_Rating,Rapid_rating,Blitz_rating,Inactive_flag,GM
0,1976.000000,2675,2646.000000,2736.000000,0,1
1,1994.000000,2658,2621.000000,2601.000000,0,1
2,1987.000000,2586,2483.000000,2483.000000,0,1
3,1998.000000,2582,2502.000000,2441.000000,0,1
4,1969.000000,2577,1931.680155,1925.155242,0,1
...,...,...,...,...,...,...
8548,1985.291732,1801,1931.680155,1925.155242,0,0
8549,1994.000000,1801,1791.000000,1765.000000,0,0
8550,1992.000000,1801,1884.000000,1824.000000,0,0
8551,2001.000000,1801,1931.680155,1925.155242,0,0
8552,1982.000000,1801,1931.680155,1925.155242,0,0

In [98]:
encoder = LabelEncoder()
data['GM'] = encoder.fit_transform(data['GM'])

In [101]:
data['Inactive_flag'] = encoder.fit_transform(data['Inactive_flag'])

In [104]:
y = data['GM']
x = data.drop('GM',axis=1)

In [105]:
x_train , x_test , y_train , y_test = train_test_split(x,y,train_size=0.3)

In [106]:
model1 = LogisticRegression(verbose=1)
model1.fit(x_train,y_train)

RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            6     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  1.77792D+03    |proj g|=  2.55385D+06

           * * *

Tit   = total number of iterations
Tnf   = total number of function evaluations
Tnint = total number of segments explored during Cauchy searches
Skip  = number of BFGS updates skipped
Nact  = number of active bounds at final generalized Cauchy point
Projg = norm of the final projected gradient
F     = final function value

           * * *

   N    Tit     Tnf  Tnint  Skip  Nact     Projg        F
    6     38     63      1     0     0   1.270D-02   8.244D+00
  F =   8.2438107901972177

CONVERGENCE: REL_REDUCTION_OF_F_<=_FACTR*EPSMCH

 This problem is unconstrained.

LogisticRegression(verbose=1)

In [115]:


y_pred1 = model1.predict(x_test)
print(f'''
      {classification_report(y_pred1,y_test)}\n\n\n
      \n\n\n Score : {model1.score(x_test,y_test)} 
      \n\n\n F1 Score : {f1_score(y_pred1,y_test)}''')

                    precision    recall  f1-score   support

           0       1.00      1.00      1.00      5964
           1       0.59      0.71      0.64        24

    accuracy                           1.00      5988
   macro avg       0.79      0.85      0.82      5988
weighted avg       1.00      1.00      1.00      5988







 Score : 0.9968269873079493



 F1 Score : 0.6415094339622641

In [121]:
svm = SVC()
svm.fit(x_train,y_train)
y_pred2 = svm.predict(x_test)

print(classification_report(y_pred2,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5988
           1       0.00      0.00      0.00         0

    accuracy                           1.00      5988
   macro avg       0.50      0.50      0.50      5988
weighted avg       1.00      1.00      1.00      5988

/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [118]:
print(f'''
F1 Score : {f1_score(y_pred2,y_test)}
Score : {svm.score(x_test,y_test)}
''')

F1 Score : 0.0
Score : 0.9951569806279225