In [21]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
data = pd.read_csv('/kaggle/input/world-university-rankings/cwurData.csv')

In [65]:
data1 = pd.read_csv('/kaggle/input/world-university-rankings/cwurData.csv')

In [13]:
data

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,996,University of the Algarve,Portugal,7,367,567,218,926,845,812,969.0,816,44.03,2015
2196,997,Alexandria University,Egypt,4,236,566,218,997,908,645,981.0,871,44.03,2015
2197,998,Federal University of Cear치,Brazil,18,367,549,218,830,823,812,975.0,824,44.03,2015
2198,999,University of A Coru침a,Spain,40,367,567,218,886,974,812,975.0,651,44.02,2015
2199,1000,China Pharmaceutical University,China,83,367,567,218,861,991,812,981.0,547,44.02,2015

In [17]:
data.drop('institution',axis=1,inplace=True)

In [29]:
data.drop('broad_impact',axis=1,inplace=True)

In [18]:

encoder = LabelEncoder()
data['country'] = encoder.fit_transform(data['country'])

In [30]:
X = data.drop('world_rank',axis=1)
Y = data['world_rank']

In [31]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [32]:
x_train , x_test , y_train , y_test  = train_test_split(X,Y,train_size=0.8)

In [33]:
model = LinearRegression()
model.fit(x_train,y_train)

print(model.score(x_test,y_test))

0.9303920851065701

First